<a href="https://colab.research.google.com/github/FertwBr/python/blob/master/Comparacao_Classificadores_Sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import make_classification

# 1) Classificador RNA - Perceptron

 a) Leitura dos dados

In [16]:
baseDados = pd.read_csv("pesquisa_satisfacao.csv", sep=";")

b) Converter SAT para 1 e INS para 0


In [17]:
baseDados['CLASSE'] = baseDados['CLASSE'].map({'SAT': 1, 'INS': 0})

c) Remover a coluna RID

In [18]:
baseDados = baseDados.drop('RID', axis=1)

e) Treinar o **Perceptron**

In [19]:
X = baseDados.drop('CLASSE', axis=1)
y = baseDados['CLASSE']
clf_perceptron = Perceptron(random_state=42)
clf_perceptron.fit(X, y)

Perceptron(random_state=42)

f) Classificar os dados

In [20]:
y_pred_perceptron = clf_perceptron.predict(X)

g) Acurácia

In [21]:
acuracia_perceptron = accuracy_score(y, y_pred_perceptron)
print(f"Acurácia Perceptron: {acuracia_perceptron}")

Acurácia Perceptron: 0.5


 h) Matriz de confusão

In [22]:
cm_perceptron = confusion_matrix(y, y_pred_perceptron)
print(f"Matriz de Confusão Perceptron:\n{cm_perceptron}")

Matriz de Confusão Perceptron:
[[6 0]
 [6 0]]


In [23]:
# 2) Classificador RNA - MLP

a) Leitura e conversão dos dados

In [24]:
play_tennis = pd.read_csv("PlayTennis.csv")
le = LabelEncoder()
for col in play_tennis.columns:
    play_tennis[col] = le.fit_transform(play_tennis[col])

 b) Criar e treinar o MLP

In [25]:
X = play_tennis.drop('Play Tennis', axis=1)
y = play_tennis['Play Tennis']

clf_mlp = MLPClassifier(alpha=1e-05, tol=1e-4, random_state=42, max_iter=1000)
clf_mlp.fit(X, y)



y_pred_mlp = clf_mlp.predict(X)
acuracia_mlp = accuracy_score(y, y_pred_mlp)

print("-" * 30)
print(f"Acurácia MLP: {acuracia_mlp}")
cm_mlp = confusion_matrix(y, y_pred_mlp)
print(f"Matriz de confusão MLP:\n{cm_mlp}")

------------------------------
Acurácia MLP: 1.0
Matriz de confusão MLP:
[[5 0]
 [0 9]]


# 3) Classificador Bayesiano

In [26]:
X, y = make_classification(n_samples=250, n_features=4, n_classes=3, n_clusters_per_class=1, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)


clf_bayes = GaussianNB()
clf_bayes.fit(X_train, y_train)

y_pred_bayes = clf_bayes.predict(X_test)
acuracia_bayes = accuracy_score(y_test, y_pred_bayes)

print("-" * 30)
print(f"Acurácia Bayesiana: {acuracia_bayes}")
cm_bayes = confusion_matrix(y_test, y_pred_bayes)
print(f"Matriz de Confusão Bayesiana:\n{cm_bayes}")

------------------------------
Acurácia Bayesiana: 0.86
Matriz de Confusão Bayesiana:
[[13  0  1]
 [ 1 17  1]
 [ 2  2 13]]


# 4) Classificador SVM

In [27]:
X, y = make_classification(n_samples=1000, n_features=3, n_informative=3, n_redundant=0, n_repeated=0, n_classes=4, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

kernels = ['linear', 'poly', 'rbf', 'sigmoid']
for kernel in kernels:
    clf_svm = SVC(kernel=kernel, random_state=42)
    clf_svm.fit(X_train, y_train)
    y_pred_svm = clf_svm.predict(X_test)
    acuracia_svm = accuracy_score(y_test, y_pred_svm)

    print("-" * 30)
    print(f"Acurácia SVM ({kernel}): {acuracia_svm}")
    cm_svm = confusion_matrix(y_test, y_pred_svm)
    print(f"Matriz de Confusão SVM ({kernel}):\n{cm_svm}")

------------------------------
Acurácia SVM (linear): 0.795
Matriz de Confusão SVM (linear):
[[39  7  5  1]
 [ 4 48  1  7]
 [ 5  1 32  3]
 [ 0  1  6 40]]
------------------------------
Acurácia SVM (poly): 0.815
Matriz de Confusão SVM (poly):
[[35  7  8  2]
 [ 3 52  0  5]
 [ 1  0 37  3]
 [ 0  6  2 39]]
------------------------------
Acurácia SVM (rbf): 0.83
Matriz de Confusão SVM (rbf):
[[38  8  6  0]
 [ 3 50  1  6]
 [ 0  0 38  3]
 [ 0  1  6 40]]
------------------------------
Acurácia SVM (sigmoid): 0.56
Matriz de Confusão SVM (sigmoid):
[[26 15  9  2]
 [14 32  0 14]
 [14  0 22  5]
 [ 1  6  8 32]]
